version: "4"
services:
  springboot:
    image: ejoh/trip-together
    container_name: trip-together
    ports:
      - "8080:8080"
    networks:
      - enjoytrip_net
    restart: "always"
    environment:
      - TZ=Asia/Seoul
#  nginx:
#    image: ejoh/docker-nginx
#    container_name: enjoytrip-nginx
#    ports:
#      - "80:80"
#    depends_on:
#      - springboot
#    networks:
#      - enjoytrip_net
#    restart: "always"
#
#  redis:
#    image: redis:alpine
#    container_name: enjoytrip-redis
#    command: redis-server --port 6379
#    hostname: redis
#    ports:
#      - "6379:6379"
#    networks:
#      - enjoytrip_net
#    restart: always
#
networks:
  enjoytrip_net:
    driver: bridge